### PR TITLE
This makes gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) happy

### PR DESCRIPTION
**Pull request by trathborne**
Closes issues #7 and #8, apparently!

### CODE REVIEW

**Comment by Civil** [comment]
I've tried to built it with newer version of GCC (11.2) and with DLSS and got few more things to fix:
1. `Source/LightDefs.h` was missing cstdint
2. `Source/DLSS.cpp` required some work on fixing whcar_t -> char_t in two places.
3. I needed to comment out `target_link_libraries(RayTracedGL1 PRIVATE libstdc++)` in CMakeLists in DLSS clause.

**Comment by arrowgent** [comment]
try compiling with DLSS off
`cmake -DRG_WITH_NVIDIA_DLSS=OFF ..`

then come back to trying to solve DLSS issue.
the only provided dlss solution is a windows.dll file
until you can find the appropriate linux dlss headers & library.so

**Comment by Civil** [comment]
I mean I've tried compiling with DLSS (I have compatible card), just wanted to mention few extra quirks I needed to apply.

**Comment by Civil** [comment]
If that matters: https://github.com/Civil/RayTracedGL1/commit/bf67b39071032794106f75c7aeca689c74cd65fe

It have all extra changes I needed to compile with DLSS support. However it's still untested as I can't run prboom with RT yet.

**Comment by arrowgent** [comment]
Civil mentioned that the main branch has changed

[SpecularReprojection](https://github.com/sultim-t/RayTracedGL1)
Updated 3 days ago by [sultim-t](https://github.com/sultim-t)

your current PR tries to merge to the old main 
[SharedLibrary](https://github.com/sultim-t/RayTracedGL1/tree/SharedLibrary)
Updated last month by [sultim-t](https://github.com/sultim-t)

**Comment by sultim-t** [comment]
Thanks for the help! :)
I've installed Linux and fixed the errors

**Pull request closed without merging**
